# Generated by Django 3.1.4 on 2020-12-11 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='insta_link',
            new_name='linkedIn_link',
        ),
    ]
