# Generated by Django 3.1.4 on 2020-12-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_auto_20201211_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='youtube_link',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
