# Generated by Django 3.1.4 on 2020-12-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiretuber',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
